# Generated by Django 4.0.5 on 2022-06-15 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('date_refueling', models.DateField(default=datetime.datetime(2022, 6, 15, 17, 53, 40, 302796))),
                ('cost_per_litr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tanked_to_max_level', models.BooleanField(default=False)),
            ],
        ),
    ]
