# Generated by Django 4.0.5 on 2022-06-23 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('date_refueling', models.DateField(default=datetime.datetime(2022, 6, 23, 18, 8, 24, 915601, tzinfo=utc))),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('cost_per_litr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tanked_to_max_level', models.BooleanField(default=False)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
    ]
