# Generated by Django 4.0.5 on 2022-06-15 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('refueling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refueling',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 18, 1, 50, 378035, tzinfo=utc)),
        ),
    ]
