# Generated by Django 4.0.5 on 2022-06-15 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('refueling', '0002_refueling_car_alter_refueling_date_refueling'),
    ]

    operations = [
        migrations.AddField(
            model_name='refueling',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 21, 34, 39, 260420, tzinfo=utc)),
        ),
    ]
