# Generated by Django 4.0.5 on 2022-06-15 21:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('refueling', '0003_refueling_price_alter_refueling_date_refueling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 21, 55, 34, 723777, tzinfo=utc)),
        ),
    ]
