# Generated by Django 4.0.5 on 2022-06-15 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('refueling', '0004_alter_refueling_date_refueling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 22, 11, 27, 25241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
