# Generated by Django 4.0.5 on 2022-06-16 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('refueling', '0005_alter_refueling_date_refueling_alter_refueling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='date_refueling',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 15, 29, 16, 511762, tzinfo=utc)),
        ),
    ]
