# Generated by Django 4.0.5 on 2022-06-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarProductionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('car_model_name', models.CharField(max_length=250)),
                ('production_year', models.IntegerField()),
                ('vin', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('type_of_fuel', models.CharField(choices=[('1', 'Petrol'), ('2', 'Gasoline')], max_length=2)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carproductiondetail')),
            ],
        ),
    ]
